name: KeepAliveMyApp

on:
    push:
      paths:
        - 'loop.txt'
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ secrets.GH_TOKEN }}

       - name: Keep Alive My App
         timeout-minutes: 350
         continue-on-error: true
         run: |
           sh KeepAlive.sh

       - name: Loop workflow
         continue-on-error: true
         run: |
              git config --global user.name ${{ secrets.GH_USERNAME }}
              git config --global user.email ${{ secrets.GH_MAIL }}
              git clone https://github.com/${GITHUB_REPOSITORY} loop
              cd loop || exit 1
              echo $(date) >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop"
              git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
